CREATE TABLE flow_definition (
    id              BIGINT NOT NULL COMMENT '主键id',
    flow_code       VARCHAR(40) NOT NULL COMMENT '流程编码',
    flow_name       VARCHAR(100) NOT NULL COMMENT '流程名称',
    model_value     VARCHAR(40) NOT NULL DEFAULT 'CLASSICS' COMMENT '设计器模型',
    category        VARCHAR(100) DEFAULT NULL COMMENT '流程类别',
    version         VARCHAR(20) NOT NULL COMMENT '流程版本',
    is_publish      TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否发布（0未发布 1已发布 9失效）',
    form_custom     CHAR(1) DEFAULT 'N' COMMENT '审批表单是否自定义',
    form_path       VARCHAR(100) DEFAULT NULL COMMENT '审批表单路径',
    activity_status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '流程激活状态（0挂起 1激活）',
    listener_type   VARCHAR(100) DEFAULT NULL COMMENT '监听器类型',
    listener_path   VARCHAR(400) DEFAULT NULL COMMENT '监听器路径',
    ext             VARCHAR(500) DEFAULT NULL COMMENT '业务扩展字段',
    create_time     DATETIME DEFAULT NULL COMMENT '创建时间',
    create_by       VARCHAR(64) DEFAULT '' COMMENT '创建人',
    update_time     DATETIME DEFAULT NULL COMMENT '更新时间',
    update_by       VARCHAR(64) DEFAULT '' COMMENT '更新人',
    del_flag        CHAR(1) DEFAULT '0' COMMENT '删除标志',
    tenant_id       VARCHAR(40) DEFAULT NULL COMMENT '租户id',
    PRIMARY KEY (id),
    KEY idx_flow_definition_tenant_code (tenant_id, flow_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程定义表';

CREATE TABLE flow_node (
    id              BIGINT NOT NULL COMMENT '主键id',
    node_type       TINYINT(1) NOT NULL COMMENT '节点类型（0开始 1中间 2结束 3互斥网关 4并行网关）',
    definition_id   BIGINT NOT NULL COMMENT '流程定义id',
    node_code       VARCHAR(100) NOT NULL COMMENT '流程节点编码',
    node_name       VARCHAR(100) DEFAULT NULL COMMENT '流程节点名称',
    permission_flag VARCHAR(200) DEFAULT NULL COMMENT '权限标识，多个用@@隔开',
    node_ratio      VARCHAR(200) DEFAULT NULL COMMENT '流程签署比例值',
    coordinate      VARCHAR(100) DEFAULT NULL COMMENT '坐标',
    any_node_skip   VARCHAR(100) DEFAULT NULL COMMENT '任意结点跳转',
    listener_type   VARCHAR(100) DEFAULT NULL COMMENT '监听器类型',
    listener_path   VARCHAR(400) DEFAULT NULL COMMENT '监听器路径',
    form_custom     CHAR(1) DEFAULT 'N' COMMENT '审批表单是否自定义',
    form_path       VARCHAR(100) DEFAULT NULL COMMENT '审批表单路径',
    version         VARCHAR(20) NOT NULL COMMENT '版本',
    create_time     DATETIME DEFAULT NULL COMMENT '创建时间',
    create_by       VARCHAR(64) DEFAULT '' COMMENT '创建人',
    update_time     DATETIME DEFAULT NULL COMMENT '更新时间',
    update_by       VARCHAR(64) DEFAULT '' COMMENT '更新人',
    ext             TEXT COMMENT '节点扩展属性',
    del_flag        CHAR(1) DEFAULT '0' COMMENT '删除标志',
    tenant_id       VARCHAR(40) DEFAULT NULL COMMENT '租户id',
    PRIMARY KEY (id),
    UNIQUE KEY uk_flow_node_def_code (definition_id, node_code),
    KEY idx_flow_node_definition (definition_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程节点表';

CREATE TABLE flow_skip (
    id             BIGINT NOT NULL COMMENT '主键id',
    definition_id  BIGINT NOT NULL COMMENT '流程定义id',
    now_node_code  VARCHAR(100) NOT NULL COMMENT '当前流程节点的编码',
    now_node_type  TINYINT(1) DEFAULT NULL COMMENT '当前节点类型',
    next_node_code VARCHAR(100) NOT NULL COMMENT '下一个流程节点的编码',
    next_node_type TINYINT(1) DEFAULT NULL COMMENT '下一个节点类型',
    skip_name      VARCHAR(100) DEFAULT NULL COMMENT '跳转名称',
    skip_type      VARCHAR(40) DEFAULT NULL COMMENT '跳转类型（PASS审批通过 REJECT退回）',
    skip_condition VARCHAR(200) DEFAULT NULL COMMENT '跳转条件',
    coordinate     VARCHAR(100) DEFAULT NULL COMMENT '坐标',
    create_time    DATETIME DEFAULT NULL COMMENT '创建时间',
    create_by      VARCHAR(64) DEFAULT '' COMMENT '创建人',
    update_time    DATETIME DEFAULT NULL COMMENT '更新时间',
    update_by      VARCHAR(64) DEFAULT '' COMMENT '更新人',
    del_flag       CHAR(1) DEFAULT '0' COMMENT '删除标志',
    tenant_id      VARCHAR(40) DEFAULT NULL COMMENT '租户id',
    PRIMARY KEY (id),
    KEY idx_flow_skip_definition (definition_id, now_node_code, next_node_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='节点跳转关联表';

CREATE TABLE flow_instance (
    id              BIGINT NOT NULL COMMENT '主键id',
    definition_id   BIGINT NOT NULL COMMENT '对应flow_definition表的id',
    business_id     VARCHAR(40) NOT NULL COMMENT '业务id',
    node_type       TINYINT(1) NOT NULL COMMENT '节点类型',
    node_code       VARCHAR(40) NOT NULL COMMENT '流程节点编码',
    node_name       VARCHAR(100) DEFAULT NULL COMMENT '流程节点名称',
    variable        TEXT COMMENT '任务变量',
    flow_status     VARCHAR(20) NOT NULL COMMENT '流程状态',
    activity_status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '流程激活状态',
    def_json        TEXT COMMENT '流程定义json',
    create_time     DATETIME DEFAULT NULL COMMENT '创建时间',
    create_by       VARCHAR(64) DEFAULT '' COMMENT '创建人',
    update_time     DATETIME DEFAULT NULL COMMENT '更新时间',
    update_by       VARCHAR(64) DEFAULT '' COMMENT '更新人',
    ext             VARCHAR(500) DEFAULT NULL COMMENT '扩展字段',
    del_flag        CHAR(1) DEFAULT '0' COMMENT '删除标志',
    tenant_id       VARCHAR(40) DEFAULT NULL COMMENT '租户id',
    PRIMARY KEY (id),
    KEY idx_flow_instance_definition (definition_id),
    KEY idx_flow_instance_business (business_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程实例表';

CREATE TABLE flow_task (
    id            BIGINT NOT NULL COMMENT '主键id',
    definition_id BIGINT NOT NULL COMMENT '对应flow_definition表的id',
    instance_id   BIGINT NOT NULL COMMENT '对应flow_instance表的id',
    node_code     VARCHAR(100) NOT NULL COMMENT '节点编码',
    node_name     VARCHAR(100) DEFAULT NULL COMMENT '节点名称',
    node_type     TINYINT(1) NOT NULL COMMENT '节点类型',
    flow_status   VARCHAR(20) NOT NULL COMMENT '流程状态',
    form_custom   CHAR(1) DEFAULT 'N' COMMENT '审批表单是否自定义',
    form_path     VARCHAR(100) DEFAULT NULL COMMENT '审批表单路径',
    create_time   DATETIME DEFAULT NULL COMMENT '创建时间',
    create_by     VARCHAR(64) DEFAULT '' COMMENT '创建人',
    update_time   DATETIME DEFAULT NULL COMMENT '更新时间',
    update_by     VARCHAR(64) DEFAULT '' COMMENT '更新人',
    del_flag      CHAR(1) DEFAULT '0' COMMENT '删除标志',
    tenant_id     VARCHAR(40) DEFAULT NULL COMMENT '租户id',
    PRIMARY KEY (id),
    KEY idx_flow_task_instance (instance_id),
    KEY idx_flow_task_definition (definition_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='待办任务表';

CREATE TABLE flow_his_task (
    id               BIGINT NOT NULL COMMENT '主键id',
    definition_id    BIGINT NOT NULL COMMENT '对应flow_definition表的id',
    instance_id      BIGINT NOT NULL COMMENT '对应flow_instance表的id',
    task_id          BIGINT NOT NULL COMMENT '对应flow_task表的id',
    node_code        VARCHAR(100) DEFAULT NULL COMMENT '开始节点编码',
    node_name        VARCHAR(100) DEFAULT NULL COMMENT '开始节点名称',
    node_type        TINYINT(1) DEFAULT NULL COMMENT '开始节点类型',
    target_node_code VARCHAR(200) DEFAULT NULL COMMENT '目标节点编码',
    target_node_name VARCHAR(200) DEFAULT NULL COMMENT '结束节点名称',
    approver         VARCHAR(40) DEFAULT NULL COMMENT '审批人',
    cooperate_type   TINYINT(1) NOT NULL DEFAULT 0 COMMENT '协作方式',
    collaborator     VARCHAR(500) DEFAULT NULL COMMENT '协作人',
    skip_type        VARCHAR(10) NOT NULL COMMENT '流转类型',
    flow_status      VARCHAR(20) NOT NULL COMMENT '流程状态',
    form_custom      CHAR(1) DEFAULT 'N' COMMENT '审批表单是否自定义',
    form_path        VARCHAR(100) DEFAULT NULL COMMENT '审批表单路径',
    message          VARCHAR(500) DEFAULT NULL COMMENT '审批意见',
    variable         TEXT DEFAULT NULL COMMENT '任务变量',
    ext              TEXT DEFAULT NULL COMMENT '业务详情',
    create_time      DATETIME DEFAULT NULL COMMENT '任务开始时间',
    update_time      DATETIME DEFAULT NULL COMMENT '审批完成时间',
    del_flag         CHAR(1) DEFAULT '0' COMMENT '删除标志',
    tenant_id        VARCHAR(40) DEFAULT NULL COMMENT '租户id',
    PRIMARY KEY (id),
    KEY idx_flow_his_task_instance (instance_id),
    KEY idx_flow_his_task_task (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='历史任务记录表';

CREATE TABLE flow_user (
    id           BIGINT NOT NULL COMMENT '主键id',
    type         CHAR(1) NOT NULL COMMENT '人员类型（1审批人 2转办人 3委托人）',
    processed_by VARCHAR(80) DEFAULT NULL COMMENT '权限人',
    associated   BIGINT NOT NULL COMMENT '任务表id',
    create_time  DATETIME DEFAULT NULL COMMENT '创建时间',
    create_by    VARCHAR(80) DEFAULT NULL COMMENT '创建人',
    update_time  DATETIME DEFAULT NULL COMMENT '更新时间',
    update_by    VARCHAR(64) DEFAULT '' COMMENT '更新人',
    del_flag     CHAR(1) DEFAULT '0' COMMENT '删除标志',
    tenant_id    VARCHAR(40) DEFAULT NULL COMMENT '租户id',
    PRIMARY KEY (id),
    KEY user_processed_type (processed_by, type),
    KEY user_associated (associated)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程用户表';

ALTER TABLE sys_workflow
    ADD COLUMN flow_instance_id BIGINT NULL AFTER process_def_id,
    ADD COLUMN flow_def_id BIGINT NULL AFTER flow_instance_id,
    ADD KEY idx_sys_workflow_flow_instance (flow_instance_id),
    ADD KEY idx_sys_workflow_process_def (process_def_id);
